### ISSUE TITLE
syncer report syncer.meta: invalid cross-device link

### ISSUE THREAD

**Issue by fast01** [pingcap/tidb-tools#108]
when try to use syncer  , it reports this error [syncer.meta: invalid cross-device link]: 

2017/04/01 12:45:42 meta.go:108: [error] save meta info to file syncer.meta failed: rename /tmp/syncer.meta077733590 syncer.meta: invalid
  3 2017/04/01 12:45:42 main.go:75: [error] rename /tmp/syncer.meta077733590 syncer.meta: invalid cross-device link 

How can i do to fix this ?

**Comment by holys** [comment]
@fast01   Hi and sorry to reply so late. It seems something wrong with https://github.com/siddontang/go/blob/master/ioutil2/ioutil.go.

You can shoot an issue there :)

Reference: https://gocn.io/article/178

**Comment by GregoryIan** [comment]
@fast01 did you set `meta = syncer.meta`, or similar to this?  
if so, you can set it to `meta = ./syncer.meta` or `abs-path/syncer.meta`. 
 Anyway this is a bug, we would fix it 😳

**Comment by GregoryIan** [comment]
fixed
