### ISSUE TITLE
在Mysql增加表格字段，同步时候报错了

### ISSUE THREAD

**Issue by sangood** [pingcap/tidb-tools#115]
在同步mysql数据，增加字段，报如下错误。进程退出了，请教如何解决呢？

alter table od_order add column `caculating_string` varchar(2) null COMMENT '计费重量体积' after `delivery_status`

报错信息如下：
2017/04/23 20:24:29 binlogsyncer.go:226: [info] begin to sync binlog from position (mysql-bin.000017, 4822480)
2017/04/23 20:24:29 binlogsyncer.go:130: [info] register slave for master server 10.29.155.206:3306
2017/04/23 20:24:29 binlogsyncer.go:559: [info] rotate to (mysql-bin.000017, 4822480)
2017/04/23 20:24:29 meta.go:113: [info] save position to file, binlog-name:mysql-bin.000017 binlog-pos:4822480 binlog-gtid:map[]
2017/04/23 20:24:29 syncer.go:579: [info] rotate binlog to (mysql-bin.000017, 4822480)
2017/04/23 20:24:29 db.go:415: [error] error while parsing sql: alter table od_order add column `caculating_string` varchar(2) null COMMENT '计费重量体积' after `delivery_status`
2017/04/23 20:24:29 main.go:75: [error] /home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:668: parse query event failed:
line 0 column 108 near "" (total length 121), position (mysql-bin.000017, 4840582)
/home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:120:

**Comment by shenli** [comment]
@sangood 目前 TiDB 在进行 Add Column 的时候，还不支持指定 Position

**Comment by sangood** [comment]
谢谢！请勿这个错误改如何解决呢？我需要重新再导入一遍数据库吗？现在启动sync就是退出进程了。

**Comment by shenli** [comment]
有两种方法：
1. 重新dump mysql 数据，然后再启动 syncer
2. 手动跳过这条 sql，但是要手动执行一下 alter 语句，注意把 after 去掉

https://github.com/pingcap/docs-cn/blob/master/op-guide/mysql-compatibility.md#ddl

**Comment by sangood** [comment]
谢谢！第一种方法比较麻烦啊，数据量比较大。
第二种方法，你说的该如何手动跳过呢？我已经在tidb里面执行了alter语句，也成功了。但是启动sync还是一样的错误。需要手动改syncer.meta吗？谢谢！
2017/04/24 10:01:14 main.go:52: [info] config: log-level:info log-file: log-rotate:day status-addr: server-id:101 worker-count:1 batch:1 meta-file:./syncer-wms.meta do-tables:[] do-dbs:[] ignore-tables:[] ignore-dbs:[] from:DBConfig(host:10.29.155.206, user:wms, port:3306, pass:<omitted>) to:DBConfig(host:10.26.151.208, user:root, port:4000, pass:<omitted>)
2017/04/24 10:01:14 binlogsyncer.go:71: [info] create BinlogSyncer with config &{101 mysql 10.29.155.206 3306 wms java$#@!  false false}
2017/04/24 10:01:14 binlogsyncer.go:226: [info] begin to sync binlog from position (mysql-bin.000017, 4822480)
2017/04/24 10:01:14 binlogsyncer.go:130: [info] register slave for master server 10.29.155.206:3306
2017/04/24 10:01:14 binlogsyncer.go:559: [info] rotate to (mysql-bin.000017, 4822480)
2017/04/24 10:01:14 meta.go:113: [info] save position to file, binlog-name:mysql-bin.000017 binlog-pos:4822480 binlog-gtid:map[]
2017/04/24 10:01:14 syncer.go:579: [info] rotate binlog to (mysql-bin.000017, 4822480)
2017/04/24 10:01:14 db.go:415: [error] error while parsing sql: alter table od_order add column `caculating_string` varchar(2) null COMMENT '计费重量体积' after `delivery_status`
2017/04/24 10:01:14 main.go:75: [error] /home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:668: parse query event failed: line 0 column 108 near "" (total length 121), position (mysql-bin.000017, 4840582)
/home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:120:

**Comment by shenli** [comment]
@GregoryIan 帮忙看一下怎么跳过单条语句？

**Comment by GregoryIan** [comment]
@sangood u can modify the syncer.meta file,  set `binlog-pos = 4840582`

**Comment by sangood** [comment]
@GregoryIan @shenli 太感谢了，昨天晚上，我自己试了改4840582 就是不行。今天竟然可以了。谢谢你们快速回复解答。第一次安装测试！碰到问题比较多。

**Comment by shenli** [comment]
@sangood Great! Feel free to contact us if you meet any problem.
