### ISSUE TITLE
Syncer [error] error while parsing sql: SAVEPOINT `trans2`

### ISSUE THREAD

**Issue by henter** [pingcap/tidb-tools#122]
```
2017/04/29 16:53:24 db.go:415: [error] error while parsing sql: SAVEPOINT `trans2`
2017/04/29 16:53:24 syncer.go:668: [warning] [skip query-sql]SAVEPOINT `trans2`  [schema]:lion
...
```

**Comment by shenli** [comment]
@henter You can ignore SAVEPOINT statement by adding rules in config file. See: https://github.com/pingcap/tidb-tools/tree/master/syncer#config

**Comment by henter** [comment]
@shenli
seems doesn't work, tried both ```skip-sqls = ["SAVEPOINT"]```  and ```skip-sqls = ["SAVEPOINT"]```

**Comment by GregoryIan** [comment]
from    ```2017/04/29 16:53:24 db.go:415: [error] error while parsing sql: SAVEPOINT `trans2`
2017/04/29 16:53:24 syncer.go:668: [warning] [skip query-sql]SAVEPOINT `trans2`  [schema]:lion
...```   
syncer has already skipped `SAVEPOINT trans2`, and TiDB doesn't support `SAVEPOINT`.  Does syncer have other error?
