### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bqwzhl20** [pingcap/tidb-tools#187]
2019/01/24 11:19:50 diff.go:258: [error] table: test_user, range: (`uid` >= ? AND `uid` < ? AND ctime >= '2017-05-09 10:39:37' AND ctime < '2019-01-23 17:40:00'), args: [151262720433299085 151753833161977213], checksum is not equal, one is 1422990440, another is 2838034901
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xc5fcfe]

goroutine 29 [running]:
github.com/pingcap/tidb-tools/pkg/dbutil.SelectUniqueOrderKey(0x0, 0xed0060, 0x11, 0xc000147b18, 0x4c6816, 0xc0001ee840, 0x0)
        /home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/pkg/dbutil/index.go:165 +0xae
github.com/pingcap/tidb-tools/pkg/diff.getChunkRows(0xfcda60, 0xc0000ac010, 0xc0001ee9c0, 0xc0002dbb00, 0xf, 0xc0002dbb40, 0x10, 0x0, 0xc00043cd20, 0x67, ...)
        /home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:541 +0x43
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).checkChunkDataEqual(0xc0000da480, 0xfcda60, 0xc0000ac010, 0xc0004f8000, 0x419, 0x1063, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:264 +0x19f
github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).EqualTableData.func1(0xc0000da480, 0xfcda60, 0xc0000ac010, 0xc0004cf3b0, 0xc0004f8000, 0x419, 0x1063)
        /home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:192 +0x73
created by github.com/pingcap/tidb-tools/pkg/diff.(*TableDiff).EqualTableData
        /home/jenkins/workspace/build_tidb_tools_master/go/src/github.com/pingcap/tidb-tools/pkg/diff/diff.go:191 +0x3e4

----------------------------------------------------------------------------------------------
1、upstream mysql： Server version: 5.7.16-log MySQL Community Server (GPL)
2、downstr mysql： Server version: 5.6.16-log Source distribution
3、./bin/sync_diff_inspector -V
INFO[0000] version: 
sync_diff_inspector: v1.0.0~rc2+git.883b07a
Git Commit Hash: 883b07a04a7382f1c0435d0ff46fe04adaef30f4
UTC Build Time: 2019-01-04 03:41:22
Go Version: go1.11.2

**Comment by july2993** [comment]
@WangXiangUSTC PTAL

**Comment by IANTHEREAL** [comment]
@WangXiangUSTC had it been fixed?

**Comment by WangXiangUSTC** [comment]
@bqwzhl20 can you provide your config file?

**Comment by WangXiangUSTC** [comment]
fixed in https://github.com/pingcap/tidb-tools/pull/195, I will close this issue, if you meet this error again, you can reopen it @bqwzhl20
