### ISSUE TITLE
多套监控冗余

### ISSUE THREAD

**Issue by lwlw217** [pingcap/tidb-tools#196]
部署测试TiDB监控时发现几个疑问：
1. 如果部署多套tidb集群，相应的监控也会部署多套（Prometheus+grafana）,是否可以将多套监控整合在一起？
2. DM的监控是否也可以和tidb的监控整合在一起，而不需要单独的再部署一套DM监控的Prometheus+grafana？

**Comment by kennytm** [comment]
PTAL @csuzhangxc

**Comment by csuzhangxc** [comment]
@wl21787 
Yes, you can deploy one cluster (Prometheus + Grafana) to monitor both TiDB and DM.
the things you need to do including:
1. tell Prometheus to pull metrics from DM, ref https://github.com/pingcap/dm/blob/master/dm/dm-ansible/roles/prometheus/templates/prometheus.yml.j2
2. add DM dashboard to Grafana, ref https://github.com/pingcap/dm/blob/master/dm/dm-ansible/scripts/dm.json

**Comment by csuzhangxc** [comment]
@wl21787 have you solved it?

**Comment by lwlw217** [comment]
还没尝试，在部署DM时遇到了问题，task无法启动。

**Comment by lwlw217** [comment]
![image](https://user-images.githubusercontent.com/21055334/52771708-8e660880-3071-11e9-8716-853364f436c9.png)

并且有几点疑问：
1. mydumper,loader,syncer单元调用的脚本应该在ansible部署安装时就已经安装好了，但是我无法找到相应的可执行文件。
2. mydumper导出的文件保存在本地的哪个文件下？

**Comment by csuzhangxc** [comment]
0. have you encrypt your passwords by dmctl? ref <https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/maintenance/dm-ansible.md#dmctl-%E5%8A%A0%E5%AF%86%E4%B8%8A%E6%B8%B8-mysql-%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81>
1. unit switching implemented in DM's binary, not outer scripts
2. `dir` config item in `loaders` section, ref: <https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/configuration/configuration.md#%E5%8A%9F%E8%83%BD%E9%85%8D%E7%BD%AE%E9%9B%86>

**Comment by lwlw217** [comment]
1. 密码已经加密
![image](https://user-images.githubusercontent.com/21055334/52772345-3a5c2380-3073-11e9-9551-5b28115f3c27.png)

2. `dir` config item in `loaders` section
![image](https://user-images.githubusercontent.com/21055334/52772627-e998fa80-3073-11e9-8799-b2823ae461c4.png)

但是错误依然出现。

**Comment by csuzhangxc** [comment]
1. Is password (`target-database`) in task YAML config encrypted?

**Comment by lwlw217** [comment]
目标数据库的密码没有加密：
![image](https://user-images.githubusercontent.com/21055334/52772981-d63a5f00-3074-11e9-930e-37465ff185e7.png)

**Comment by csuzhangxc** [comment]
in DM, all passwords for the database should be encrypted.

**Comment by lwlw217** [comment]
多谢！
问题已经解决。
