### ISSUE TITLE
无法使用checker检测数据库，连接拒绝

### ISSUE THREAD

**Issue by smcdl** [pingcap/tidb-tools#20]
checker.go:202: [error] query sql[show tables;] failed dial tcp 127.0.0.1:3306: connect: connection refused
总是显示这句，我能十分肯定我的mysql服务可以使用root用户正常连接。

**Comment by holys** [comment]
请问您执行 checker 的命令是啥？ 以及您的mysql 版本是？

**Comment by smcdl** [comment]
我的错，我的port不是3306，我用mysql命令连接的时候走的是sock
