### ISSUE TITLE
checker 工具是否被删除了?

### ISSUE THREAD

**Issue by zhuozl** [pingcap/tidb-tools#213]

**Comment by zhuozl** [comment]
在看官方文档的时候，https://pingcap.com/docs-cn/v2.1/op-guide/migration-overview/#%E4%BD%BF%E7%94%A8-checker-%E8%BF%9B%E8%A1%8C-schema-%E6%A3%80%E6%9F%A5

发现有一个checker 工具，master 分支没有．

**Comment by WangXiangUSTC** [comment]
the checker have already be moved because long time no maintenance. We have move it to a pkg https://github.com/pingcap/tidb-tools/tree/master/pkg/check, maybe we will rebuild a new checker later. now need check by artificial @zhuozl

**Comment by zhuozl** [comment]
@WangXiangUSTC  thanks.
