### ISSUE TITLE
停止drainer和pump后，再次启动失败

### ISSUE THREAD

**Issue by YuanDdQiao** [pingcap/tidb-tools#218]
base on tidb-binlog tools.
1. i'm installed success from https://pingcap.github.io/docs-cn/tools/tidb-binlog-cluster/

    when i  'ansible-playbook stop_drainer.yml' ,then 'rm -rf drainer.toml'

    now i'm running 'ansible-playbook start_drainer.yml' ,but it's don't work!.
2. and ,i'm running 'ansible-playbook stop.yml --tags=pump'  then 
  
   but i'm running 'ansible-playbook start.yml' then,it's does't work too. 

so, i'm getting the pump status from pd-server  ,thant's 'State: paused'

.i don't how to  get start them, can you give me start method ,please..

thank you, very much.

**Comment by YuanDdQiao** [comment]
base on tidb-binlog tools.

i'm installed success from https://pingcap.github.io/docs-cn/tools/tidb-binlog-cluster/

when i 'ansible-playbook stop_drainer.yml' ,then 'rm -rf drainer.toml'

now i'm running 'ansible-playbook start_drainer.yml' ,but it's don't work!.

and ,i'm running 'ansible-playbook stop.yml --tags=pump' then

but i'm running 'ansible-playbook start.yml' then,it's does't work too.

so, i'm getting the pump status from pd-server ,thant's 'State: paused'

.i don't how to get start them, can you give me start method ,please..

thank you, very much.

**Comment by YuanDdQiao** [comment]
@gregwebs hello ，anyone, please ,i'm waitting for you anwser this question..

**Comment by WangXiangUSTC** [comment]
1. why 'rm -rf drainer.toml'? you need execute `ansible-playbook deploy_drainer.yml` first
2. what is the mean of `it's does't work`, can you provide some log

**Comment by YuanDdQiao** [comment]
1.  i'm deploy drainer ,and then i'm start drainer...
drainer.log:
no message..


  and i'm run 'ansible-playbook start_drainer.yml' get  :
TASK [wait until the drainer port is up] *************************************************************************************************************************************************************************************************************************************
fatal: [drainer_mysql]: FAILED! => {"changed": false, "elapsed": 300, "msg": "the drainer port 8249 is not up"}
	to retry, use: --limit @/home/tidb/tidb-ansible-01/retry_files/start_drainer.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
172.19.116.241             : ok=3    changed=0    unreachable=0    failed=0   
172.19.243.118             : ok=3    changed=0    unreachable=0    failed=0   
172.19.243.119             : ok=3    changed=0    unreachable=0    failed=0   
172.19.243.126             : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.127              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.128              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.129              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.130              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.131              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.132              : ok=3    changed=0    unreachable=0    failed=0   
drainer_mysql              : ok=4    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   


ERROR MESSAGE SUMMARY ********************************************************************************************************************************************************************************************************************************************************
[172.19.116.241]: Ansible UNREACHABLE! => playbook: start.yml; TASK: wait until the pump port is up; message: {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to 172.19.116.241 closed.", "unreachable": true}

[drainer_mysql]: Ansible FAILED! => playbook: start_drainer.yml; TASK: wait until the drainer port is up; message: {"changed": false, "elapsed": 300, "msg": "the drainer port 8249 is not up"}

Ask for help:
Contact us: support@pingcap.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the tidb-ansible/inventory.ini and tidb-ansible/log/ansible.log files and the error message, or new issue on https://github.com/pingcap/tidb-ansible/issues. We'll try our best to help you deploy a TiDB cluster. Thanks. :-)
[tidb@dm-ctl-center tidb-ansible-01]$ 


2.  when i'm start pump...
pump.log:
2019/03/19 13:13:35 version.go:18: [info] Git Commit Hash: b31065a65583127fdc0b3bdb2214f667003b8c18
2019/03/19 13:13:35 version.go:19: [info] Build TS: 2019-03-13 02:27:36
2019/03/19 13:13:35 version.go:20: [info] Go Version: go1.11.2
2019/03/19 13:13:35 version.go:21: [info] Go OS/Arch: linuxamd64
2019/03/19 13:13:35 server.go:103: [info] clusterID of pump server is 6668543388743062343
2019/03/19 13:13:35 storage.go:124: [info] storage config: &{KVConfig:{BlockCacheCapacity:8388608 BlockRestartInterval:16 BlockSize:4096 CompactionL0Trigger:8 CompactionTableSize:67108864 CompactionTotalSize:536870912 CompactionTotalSizeMultiplier:8 WriteBuffer:67108864 WriteL0PauseTrigger:24 WriteL0SlowdownTrigger:17}}
2019/03/19 13:13:35 storage.go:194: [info] gcTS: 406968349340467200, maxCommitTS: 407081883769765889, headPointer: {Fid:0 Offset:158400}, handlePointer: {Fid:0 Offset:158400}
2019/03/19 13:13:35 server.go:309: [info] register success, this pump's node id is dm-master:8250
2019/03/19 13:13:35 node.go:147: [info] start try to notify drainer:  172.19.116.243:8249 
2019/03/19 13:13:35 main.go:59: [error] pump server error, fail to notify all living drainer: notify drainer(172.19.116.243:8249); but return error(rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp drainerip:8249: connect: connection refused")

**Comment by YuanDdQiao** [comment]
i can't start pump \drainer anyone .

**Comment by WangXiangUSTC** [comment]
please provide drainer's log

**Comment by YuanDdQiao** [comment]
THE log ：
[root@dm-worker-01 conf]# tail -f /data/deploy/log/drainer.log 
2019/03/18 14:44:08 syncer.go:297: [info] [write save point]407081175784357889
2019/03/18 14:44:11 syncer.go:297: [info] [write save point]407081176570789889
2019/03/18 14:44:14 syncer.go:297: [info] [write save point]407081177357221889
2019/03/18 14:44:17 syncer.go:297: [info] [write save point]407081178143653889
2019/03/18 14:44:20 syncer.go:297: [info] [write save point]407081178930085889
2019/03/18 14:44:23 syncer.go:297: [info] [write save point]407081179716517889
2019/03/18 14:44:26 syncer.go:297: [info] [write save point]407081180502949889
2019/03/18 14:44:29 syncer.go:297: [info] [write save point]407081181289381889
2019/03/18 14:44:32 syncer.go:297: [info] [write save point]407081182088921089
2019/03/18 14:44:32 syncer.go:300: [fatal] [write save point]407081182088921089[error]Error 1146: Table 'tidb_binlog.checkpoint' doesn't exist

not current log message.

**Comment by WangXiangUSTC** [comment]
1. do you drop tidb_binlog.checkpoint table in downstream when drainer is running?
2. you can restart drainer, drainer will create this table.

**Comment by YuanDdQiao** [comment]
en\en.   i want to re-deploy tidb-cluster and  dm- and  tidb-binlog。

when i get same new question ,i will request to you ,,
thank you, very much

**Comment by WangXiangUSTC** [comment]
ok, I will close this issue. if you meet new problem you can reopen this or create a new issue

**Comment by YuanDdQiao** [comment]
thanks bye

**Comment by YuanDdQiao** [comment]
hello ,
sorry ,i'm comming again.

first, i gots re-deployed .
but,when i deploy and start_pump ,it's no problem,
and i deploy drainer it's also success,,then
i get start drainer ,it's fails:



TASK [start drainer by systemd] ************************************************************************************************************************************************************
ok: [mysqltest]

TASK [wait until the drainer port is up] ***************************************************************************************************************************************************
fatal: [mysqltest]: FAILED! => {"changed": false, "elapsed": 300, "msg": "the drainer port 8249 is not up"}
	to retry, use: --limit @/home/tidb/tidb-ansible-01/retry_files/start_drainer.retry

PLAY RECAP *********************************************************************************************************************************************************************************
172.19.243.118             : ok=3    changed=0    unreachable=0    failed=0   
172.19.243.119             : ok=3    changed=0    unreachable=0    failed=0   
172.19.243.126             : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.127              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.128              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.129              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.130              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.131              : ok=3    changed=0    unreachable=0    failed=0   
172.19.30.132              : ok=3    changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
mysqltest                  : ok=4    changed=0    unreachable=0    failed=1   
pump1                      : ok=3    changed=0    unreachable=0    failed=0   


ERROR MESSAGE SUMMARY **********************************************************************************************************************************************************************
[mysqltest]: Ansible FAILED! => playbook: start_drainer.yml; TASK: wait until the drainer port is up; message: {"changed": false, "elapsed": 300, "msg": "the drainer port 8249 is not up"}

Ask for help:
Contact us: support@pingcap.com


it's not print log on drainer machine ,

and pump log message:
.....
LevelDurations:[]}
2019/03/19 16:11:12 server.go:496: [info] writeBinlogCount: 0, alivePullerCount: 0,  maxCommitTS: 407105193868787713
.....

no more other message .

**Comment by WangXiangUSTC** [comment]
drainer's log file is empty?

**Comment by YuanDdQiao** [comment]
no drainer's log file.

**Comment by YuanDdQiao** [comment]
[root@dm-worker-01 db]# ls -al 
total 36
drwxr-xr-x 9 tidb tidb 4096 Mar 19 15:41 .
drwxr-xr-x 4 tidb tidb 4096 Mar 19 15:39 ..
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:39 backup
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 bin
drwxr-xr-x 2 tidb tidb 4096 Mar 19 16:22 conf
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 data.drainer
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 log
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 scripts
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 status
[root@dm-worker-01 db]# ls -al log/
total 8
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 .
drwxr-xr-x 9 tidb tidb 4096 Mar 19 15:41 ..
[root@dm-worker-01 db]#

**Comment by WangXiangUSTC** [comment]
[tidb@ip-127-0-0-1 deploy]$ pwd
/data1/tidb/deploy
[tidb@ip-127-0-0-1 deploy]$ sh scripts/start_drainer.sh

can you execute the `start_drainer.sh` by manual

**Comment by YuanDdQiao** [comment]
[root@dm-worker-01 db]# sh scripts/start_drainer.sh
[root@dm-worker-01 db]# ps aux^C
[root@dm-worker-01 db]# ls-al l^C
[root@dm-worker-01 db]# ls -al log/
total 8
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 .
drwxr-xr-x 9 tidb tidb 4096 Mar 19 15:41 ..
[root@dm-worker-01 db]# pwd
/data/deploy/db
[root@dm-worker-01 db]# ls -al 
total 36
drwxr-xr-x 9 tidb tidb 4096 Mar 19 15:41 .
drwxr-xr-x 4 tidb tidb 4096 Mar 19 15:39 ..
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:39 backup
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 bin
drwxr-xr-x 2 tidb tidb 4096 Mar 19 16:22 conf
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 data.drainer
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 log
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 scripts
drwxr-xr-x 2 tidb tidb 4096 Mar 19 15:41 status
[root@dm-worker-01 db]# ps aux|grep drainer
root      4036  0.0  0.0 112708   976 pts/0    S+   17:36   0:00 grep --color=auto drainer
[root@dm-worker-01 db]#

**Comment by YuanDdQiao** [comment]
and ...

[tidb@dm-ctl-center dm-ansible]$   /home/tidb/tidb-ansible-01/resources/bin/binlogctl -pd-urls=http://172.19.30.131:2379 -cmd drainer
[tidb@dm-ctl-center dm-ansible]$   /home/tidb/tidb-ansible-01/resources/bin/binlogctl -pd-urls=http://172.19.30.131:2379 -cmd pumps
INFO[0000] pump: {NodeID: dm-master:8250, Addr: 172.19.116.241:8250, State: online, MaxCommitTS: 407106697408806913, UpdateTime: 2019-03-19 17:46:45 +0800 CST} 
[tidb@dm-ctl-center dm-ansible]$

**Comment by YuanDdQiao** [comment]
and .....

[root@dm-worker-01 db]# cat scripts/run_drainer.sh 
#!/bin/bash
set -e
ulimit -n 1000000

DEPLOY_DIR=/data/deploy/db

cd "${DEPLOY_DIR}" || exit 1

exec bin/drainer \
    --addr="172.19.116.243:8249" \
    --pd-urls="http://172.19.30.131:2379,http://172.19.30.130:2379,http://172.19.30.132:2379" \
    --data-dir="/data/deploy/db/data.drainer" \
    --log-file="/data/deploy/db/log/drainer.log" \
    --config=conf/drainer.toml \
    --initial-commit-ts="407104578013888513"

**Comment by WangXiangUSTC** [comment]
1.  /home/tidb/tidb-ansible-01/resources/bin/binlogctl -pd-urls=http://172.19.30.131:2379 -cmd drainers
it is `drainers`, not `drainer`.

2. the drainer.log is also empty?

**Comment by YuanDdQiao** [comment]
1.

> 1. /home/tidb/tidb-ansible-01/resources/bin/binlogctl -pd-urls=http://172.19.30.131:2379 -cmd drainers
>    it is `drainers`, not `drainer`.
> 2. the drainer.log is also empty?

no drainer.
and no drainer.log file.

**Comment by YuanDdQiao** [comment]
is that os-linux problem?

**Comment by YuanDdQiao** [comment]
[tidb@dm-ctl-center dm-ansible]$   /home/tidb/tidb-ansible-01/resources/bin/binlogctl -pd-urls=http://172.19.30.131:2379 -cmd drainers
[tidb@dm-ctl-center dm-ansible]$ 

return the same it

**Comment by superlzs0476** [comment]
Which one of tidb-ansible version?

**Comment by YuanDdQiao** [comment]
[root@dm-master ~]# /data/deploy/dm/bin/dm-master  -V
Release Version: v1.0.0-alpha-30-g76218b6
Git Commit Hash: 76218b641f3f511aca723ad07599ea3ed8df1bcb
Git Branch: master
UTC Build Time: 2019-03-14 03:48:13
Go Version: go version go1.12 linux/amd64

**Comment by YuanDdQiao** [comment]
[tidb@dm-ctl-center dm-ansible]$ ansible --version
ansible 2.6.14
  config file = /home/tidb/dm-ansible/ansible.cfg
  configured module search path = [u'/home/tidb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[tidb@dm-ctl-center dm-ansible]$

**Comment by superlzs0476** [comment]
What is the branch of tidb-ansible ?

**Comment by YuanDdQiao** [comment]
master

**Comment by superlzs0476** [comment]
Please execute follow command and upload output result.
1.  Which one of pump model cluster or kafka ?
2. output result about "ansible-playbook start_drainer.yml -vvvv "
3. output result about " sh -x run_run_drainer.sh"
