### ISSUE TITLE
is there a way to sync only selected tables in a db?

### ISSUE THREAD

**Issue by Dnile** [pingcap/tidb-tools#23]
for example:
 database a has tables `b,c,d,e`
 i would like to sync only the `b` table into a different host.

**Comment by siddontang** [comment]
Hi @Dnile 

Syner has not supported this, but we will plan to do this soon.

**Comment by Dnile** [comment]
thanks for the quick reply @siddontang !
i'll keep following, but also would love to land a hand, if there's anything can do to help this please point me as to where i should start :)

**Comment by siddontang** [comment]
Hi @Dnile 

We have already supported this feature, you can try it now.
