### ISSUE TITLE
column mapping expression添加默认值

### ISSUE THREAD

**Issue by aladingg** [pingcap/tidb-tools#233]
## Feature Request

**由于历史原因，有2种不完全的分库分表实施方案：
1.分库名无后缀，表名有后缀，例如2个分库都为store，分库中的表名分别 为log_1，log_2
2.分库名有后续，表名无后缀，例如2个分库为store_1，store_2，分库中的表名都为log

**data migration工具强制要求分库分表有数字后缀，所以不支持以上2种情况的合并操作

**建议2种方案修改：
1. 在prefix==name的情况下，将schema id和table id默认为0，具体修改点在pkg/column-mapping/column.go文件，函数为computeID
2. 添加新的expression :-D

望采纳，谢谢！

**Comment by kennytm** [comment]
Column mapping supports using `null` or empty string `""` to skip assigning the schema/table IDs. So in your cases you could write:

1. `["1", "", "log_"]`
2. `["1", "store_", ""]`

**Comment by aladingg** [comment]
> Column mapping supports using `null` or empty string `""` to skip assigning the schema/table IDs. So in your cases you could write:
> 
> 1. `["1", "", "log_"]`
> 2. `["1", "store_", ""]`

thx a lot, and this ran perfectly:-)
