### ISSUE TITLE
Add a command line argument to switch flavor to MariaDB

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb-tools#25]
MariaDB on macOS. syncer failed to sync from MariaDB to a local TiDB memory instance.

syncer quits with exit code 0:

```
2016/11/04 18:34:55 syncer.go:611: [debug] [query]BEGIN
2016/11/04 18:28:25 syncer.go:611: [debug] [query]# Dum
2016/11/04 18:28:25 main.go:79: [error] /gopath/src/github.com/pingcap/tidb-tools/syncer/syncer.go:615: parse query event failed: [sql]# Dum[error][parser:1]syntax error
/gopath/src/github.com/pingcap/tidb-tools/syncer/syncer.go:122:
```

``QueryEvent.Query`` gives: ``b"# Dum"``.

MariaDB config:

```
// Server version: 10.1.18-MariaDB Homebrew
[mysqld]
server-id=1
datadir=/usr/local/var/mysql
log-bin=mysql-bin
binlog_format=row
max_binlog_size = 20M
max_allowed_packet = 30M
```

**Comment by ngaut** [comment]
Thank you!, Could you fix it ?

**Comment by andelf** [comment]
Solved by changing https://github.com/pingcap/tidb-tools/blob/master/syncer/syncer.go#L480 to ``"mariadb"``.

We need a command line argument to specify DB flavor.

**Comment by andelf** [comment]
I checked the binlog file using ``mysqbinlog`` both from MySQL & MariaDB. The ``# Dum`` string comes from a GTID event of MariaDB.

And I found this:

a related issue: [MDEV-4487](https://mariadb.atlassian.net/browse/MDEV-4487)

Key point: 

>  it breaks on the first GTID-related event (e.g. 'Previous_gtids' or 'Gtid')

:(

A work around may be adding ``# `` to sql skip prefixes (``syncer.go``). It works on my laptop.
