### ISSUE TITLE
RELOAD 权限检查过于严格

### ISSUE THREAD

**Issue by Dieken** [pingcap/tidb-tools#270]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

DM 连接的源数据库使用的账户如果没有 RELOAD 权限，DM 会报错，虽然 DM 有 ignore-checking-items 选项可以忽略掉 dump_privilege 的检查，但这个选项对应 RELOAD + SELECT，会也跳过 SELECT 的检查。

2. What did you expect to see?

对 RELOAD 权限跟文档描述的应该一致，是可选的权限，如果没有，输出警告即可。

3. What did you see instead?

没有 RELOAD 时 DM task 启动失败。

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

2.1.15。

5. which tool are you using?

TiDB DM.

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

2.1.15。

**Comment by Dieken** [comment]
可选的 RELOAD 这个文档记载的行为是在 tidb-tools c6a5fcbcbddb78dcc2894627c06d79b697acb1eb 这个版本被改坏的。

**Comment by csuzhangxc** [comment]
@Dieken thanks for your feedback. we are trying to mark `READLOAD` as a required privilege only in `all`/`full` task mode.

**Comment by Dieken** [comment]
@csuzhangxc 

代码里 RELOAD 权限只用在全量导出的 flush tables with read lock 命令，对增量没有意义，所以增量自然不需要 RELOAD 权限，但是对于全量导出，RELOAD 应该也是如文档描述为可选的，因为：

1.  绝大部分用户都在使用 InnoDB 引擎，一般不会将 MyISAM 引擎的 mysql-5.7 的 "mysql" db 导入 TiDB，因此是可以通过事务来达到快照一致性的，不需要锁表。

2.  阿里云 RDS 压根不给 RELOAD 权限，其它云服务上的 RDS 不清楚。如果 TiDB DM 要求全量导出必须有 RELOAD 权限，那么问题显而易见。
