### ISSUE TITLE
make sync_diff_inspector failed

### ISSUE THREAD

**Issue by xialuo1990** [pingcap/tidb-tools#275]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
build github.com/pingcap/tidb-tools/sync_diff_inspector: cannot load github.com/pingcap/pd/pd-client: cannot find module providing package github.com/pingcap/pd/pd-client
make: *** [sync_diff_inspector] Error 1

2. What did you expect to see?
make success

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by WangXiangUSTC** [comment]
you can execute `make` to build all tools, or execute `cp go.mod1 go.mod` and `cp go.sum1 go.sum` and then `make sync_diff_inspector`

**Comment by july2993** [comment]
> you can execute `make` to build all tools, or execute `cp go.mod1 go.mod` and `cp go.sum1 go.sum` and then `make sync_diff_inspector`

If then we should update the  README.md.

**Comment by dveeden** [comment]
@july2993 @WangXiangUSTC  Maybe something like this could fix this?
```diff
diff --git a/Makefile b/Makefile
index 9db34fe..054492f 100644
--- a/Makefile
+++ b/Makefile
@@ -61,7 +61,7 @@ importer:
 dump_region:
        $(GO) build -ldflags '$(LDFLAGS)' -o bin/dump_region ./dump_region
 
-sync_diff_inspector:
+sync_diff_inspector: prepare
        $(GO) build -ldflags '$(LDFLAGS)' -o bin/sync_diff_inspector ./sync_diff_inspector
 
 ddl_checker:
```

**Comment by jebter** [comment]
Please try the latest version. I will close it, if there are any updates, you can reopen it.
