### ISSUE TITLE
sync_diff_inspector: check supported column types before the run

### ISSUE THREAD

**Issue by george24601** [pingcap/tidb-tools#314]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Our sync diff inspector produced a large fix.sql because we didn't include json columns in the `ignore_columns` option

**Describe the feature you'd like:**
Before the checksum run, check target table's column types, and make sure it is not one of the [unsupported columns](https://pingcap.com/docs/stable/reference/tools/sync-diff-inspector/overview/)

**Describe alternatives you've considered:**

Make sure `CRC32(json_field)` produces the same result in mysql and tidb. We ran into cases where the checksum is different even with the same charset and collation

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WangXiangUSTC** [comment]
thanks for your suggestion, I will take a look

**Comment by dveeden** [comment]
This is related to #350 and #435
