### ISSUE TITLE
avoid save table sumamary info failed warn log at start up

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-tools#354]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
no warn log

3. What did you see instead?
```
[2020/06/16 04:22:34.399 +00:00] [WARN] [diff.go:654] ["save table summary info failed"]
...
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?
sync-diff
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by july2993** [comment]
cc @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
fix in https://github.com/pingcap/tidb-tools/pull/355

**Comment by WangXiangUSTC** [comment]
reason：
1. diff will update and print summary info every 10 seconds, and the summary info is calculated by select chunk table.
2. diff will save chunk's information to chunk table after all chunk is split.

when update summary info, the table may not finish split chunk, so there is no data in chunk table, and diff will print warn log, users may be confused by this.
