### ISSUE TITLE
sync-diff-inspector: do not fatal "sourceDB don't equal targetDB" if failed to check

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-tools#357]
https://github.com/pingcap/tidb-tools/blob/master/sync_diff_inspector/main.go#L62
if failed to check it "		log.Fatal("sourceDB don't equal targetDB") too.

this doesn't mean don't equal. 
distinguish don't equal and failed to check.

**Comment by WangXiangUSTC** [comment]
fixed in #366
