### ISSUE TITLE
change UseCheckpoint from false to true will not use checkpoint actually

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-tools#358]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- change UseCheckpoint from false to true
- re-run sync-diff
- it will not use checkpoint actually

also, need document when it will do use checkpoint.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?
sync-diff
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by WangXiangUSTC** [comment]
diff will calculate the config hash and save in the `summary` table, if the hash changed, diff will delete data in checkpoint table, and split chunk and check again.

update `use-checkpoint` changed the config hash, and I fix it in https://github.com/pingcap/tidb-tools/pull/355
