### ISSUE TITLE
sync-diff should log config at start up

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-tools#360]
## Feature Request

**Is your feature request related to a problem? Please describe:**

sync-diff can log config at start up.

so it can easy to check the config from the log

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WangXiangUSTC** [comment]
fixed in https://github.com/pingcap/tidb-tools/pull/364
