### ISSUE TITLE
avoid the slow query warn log in sycn-diff

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-tools#361]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

many
```
[2020/06/18 03:49:33.670 +00:00] [WARN] [common.go:651] ["exec sql slow"] [sql="REPLACE INTO `sync_diff_inspector`.`chunk` VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?);"]......
...
..
```
2. What did you expect to see?
no such many annoying warn log, and this is fine actually

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?
sync-diff
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by WangXiangUSTC** [comment]
fixed in #364
