### ISSUE TITLE
lightning import failed when tikv net delay 100ms

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tidb-tools#388]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
we simulate the network delay of two places and three centers in remote computer rooms(100ms)，and import csv file use lightning tools（importer mode）
2. What did you expect to see?

![21599112696_ pic_hd](https://user-images.githubusercontent.com/50897894/92077788-b05be300-edef-11ea-8729-34bae9a528ff.jpg)

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by King-Dylan** [comment]
![21599112696_ pic_hd](https://user-images.githubusercontent.com/50897894/92077852-d1243880-edef-11ea-8726-935aa5601218.jpg)

**Comment by lance6716** [comment]
Hi, lightning's repo is https://github.com/pingcap/tidb-lightning/
