### ISSUE TITLE
Can not find syncer

### ISSUE THREAD

**Issue by clearlylin** [pingcap/tidb-tools#4]
文档介绍，说在这里的
https://segmentfault.com/a/1190000008169097

**Comment by IANTHEREAL** [comment]
Syncer is a private project now. if u want to try it, [see this document](https://github.com/pingcap/docs-cn/blob/master/tools/syncer.md)

**Comment by clearlylin** [comment]
😔
You guys are a bit too much.

**Comment by holys** [comment]
@clearlylin You might be interested in this project: https://github.com/siddontang/go-mysql  
The article you mentioned above mostly talked about `go-mysql`, not syncer.

**Comment by clearlylin** [comment]
OK.
Thanks
