### ISSUE TITLE
sync_diff_inspector: should append LIMIT 1 for DELETE in fix.sql

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb-tools#443]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by Leavrth** [comment]
done by v2.
