### ISSUE TITLE
sync-diff log level incorrect, "data  equal =false" log is INFO which is not expected

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tidb-tools#497]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
If there's data fail, log level at least is warn, what's more, error is better.

3. What did you see instead?
When there's log like "data equal = false, check failed num > 0", these log level is info not error.
[2021/08/31 21:10:34.909 +00:00] [INFO] [report.go:87] ["table check result"] [schema=test_betting_0] [table=unit14_0_game_bets_game_tag_analysis_4] ["struct equal"=true] ["data equal"=false]
[2021/09/01 12:30:09.150 +00:00] [INFO] [report.go:80] ["check result summary"] ["check passed num"=10199] ["check failed num"=1]

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 4.0.14
5. which tool are you using?
  sync-diff: ["Release Version"=v5.2.0] ["Git Commit Hash"=915b22e4d42c1493edf90f1ccc79227e55e217ba] ["Git Branch"=HEAD] ["UTC Build Time"="2021-08-13 06:09:52"]
6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by Leavrth** [comment]
sync-diff-inspector v1 had been stopped for maintenance
