### ISSUE TITLE
sync-diff check failed because  [error="invalid connection"] which is not expected

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tidb-tools#499]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

- Run sync-diff to compare data between two TiDB clusters.

2. What did you expect to see?

3. What did you see instead?

- The last log is: check failed.  -> for use, it means data inconsistency, but actually the reason is invalid connection not data inconsistency, which makes confuse to user.
[2021/09/01 07:23:53.924 +00:00] [ERROR] [diff.go:636] ["check failed"] [table=`test_betting_0`.`unit1_24_game_bets_game_tag_15`] [error="invalid connection"]

- sync-diff check result should properly hold this error "invalid connection".

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

- sync-diff 5.2.0

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by Leavrth** [comment]
the version is sync-diif-inspector v1.0, which has stopped updating.
