### ISSUE TITLE
Improve replication filtering rules

### ISSUE THREAD

**Issue by iamxy** [pingcap/tidb-tools#50]
- [x] ignore system database like `mysql` by default
- [x] support for `--replicate-ignore-db` and `--replicate-ignore-table`
- [x] wildcard is simpler than regex for users
- [x] don't forget to update docs

Ref: http://dev.mysql.com/doc/refman/5.7/en/replication-rules.html

**Comment by holys** [comment]
All tasks were implemented. Closed this issue.
