### ISSUE TITLE
sync_diff_inspector对比float类型异常

### ISSUE THREAD

**Issue by Clannadyf** [pingcap/tidb-tools#565]
问题：sync_diff_inspector对比mysql分表场景。源数据库表记录和目标数据库分表记录查询数据显示一致，select  * into file分别导出查看数据也一致，但是sync_diff_inspector显示该两条数据为差异数据，在sync_diff_inspector日志中，该两条数据的部分float类型字段小数位不一致。

sync_diff_inspector日志：
此处，sinew_trunk，bodyfat_trunk小数位不一致
2021/12/10 18:26:02.370 +08:00] [WARN] [utils.go:442] ["find different row"] [column=] [row1="{bodyfat_left_leg: 6.13725, bodyfat_right_leg: 6.19532, resistance20_right_arm: 483.8, resistance100_left_leg: 287.1, right_weight_percent: 0, sinew_left_leg: 5.07133, **sinew_trunk: 14.2204**, updated_at: 2020-12-16 02:42:26, left_weight_percent: 0, sinew_left_arm: 1.28461, sinew_right_leg: 5.17873, resistance20_trunk: 34.1, resistance100_left_arm: 454.5, category: 0, origin_resistances: IsNull, resistance100_right_leg: 275.3, resistance100_trunk: 30.4, created_at: 2020-12-16 02:42:26, pregnant_flag: 0, measurement_ext_id: 2598527, resistance20_left_arm: 493.6, **bodyfat_trunk: 14.0422**, resistance20_left_leg: 327.4, resistance100_right_arm: 439.4, bodyfat_left_arm: 2.39128, bodyfat_right_arm: 2.32071, sinew_right_arm: 1.32701, resistance20_right_leg: 311.3, timestamp: 1608086388,  }"] [row2="{ bodyfat_right_arm: 2.32071, **sinew_trunk: 14.22035**, resistance100_trunk: 30.4, created_at: 2020-12-16 02:42:26, category: 0, sinew_right_leg: 5.17873, bodyfat_right_leg: 6.19532, resistance20_right_arm: 483.8, pregnant_flag: 0, origin_resistances: IsNull, bodyfat_left_leg: 6.13725, sinew_left_leg: 5.07133, resistance20_left_arm: 493.6, resistance20_trunk: 34.1, resistance100_right_leg: 275.3, right_weight_percent: 0, sinew_right_arm: 1.32701, resistance20_right_leg: 311.3, measurement_ext_id: 2598527, **bodyfat_trunk: 14.04222**, resistance20_left_leg: 327.4, updated_at: 2020-12-16 02:42:26, sinew_left_arm: 1.28461, resistance100_right_arm: 439.4, bodyfat_left_arm: 2.39128, resistance100_left_arm: 454.5, resistance100_left_leg: 287.1, left_weight_percent: 0, timestamp: 1608086388,  }"

select * into file 导出源数据与目标分表数据，一致。
源数据：
2598527,2.39128,6.13725,2.32071,6.19532,**14.0422**,1.28461,5.07133,1.32701,5.17873,14.2204,493.6,327.4,483.8,311.3,34.1,454.5,287.1,439.4,275.3,30.4,"2020-12-16 02:42:26","2020-12-16 02:42:26",0,0,0,0,"N,1608086388

目标分表数据：
2598527,2.39128,6.13725,2.32071,6.19532,**14.0422**,1.28461,5.07133,1.32701,5.17873,14.2204,493.6,327.4,483.8,311.3,34.1,454.5,287.1,439.4,275.3,30.4,"2020-12-16 02:42:26","2020-12-16 02:42:26",0,0,0,0,"N,1608086388

**Comment by Leavrth** [comment]
请问有 float 类型列以外的列出现对比不一致嘛
