### ISSUE TITLE
Sync diff need to support charset GBK

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tidb-tools#584]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
use sync-diff to check charset GBK

2. What did you expect to see?
sync diff can work success

3. What did you see instead?
[FATAL] [main.go:95] ["failed to initialize diff process"] [error="get table test_db1.test_table2's information error [parser:1115]Unknown character set: 'gbk'

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by Leavrth** [comment]
the same as https://github.com/pingcap/tidb-tools/issues/572
