### ISSUE TITLE
question of the guide of syncer 

### ISSUE THREAD

**Issue by goldwinner** [pingcap/tidb-tools#59]
在官方文档：https://pingcap.com/docs-cn/tools/syncer/#syncer-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 里面的“配置 Syncer 监控与告警”段落

能否详细解释一下这个expr表达式是什么意思？谢谢！
 IF  syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1

**Comment by WangXiangUSTC** [comment]
same with https://github.com/pingcap/tidb/issues/7567
you can take a look
