### ISSUE TITLE
schemacmp.Table.String() return incorrect `create table` SQL

### ISSUE THREAD

**Issue by okJiang** [pingcap/tidb-tools#590]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

	In DM

	1. create table 
	  ```sql
	  create table precheck_optimistic_tb_1(a INT, b INT, primary key a(a));
	  ```
	2. get `tableInfo` from GetTableInfoBySQL
	3. encode `tableInfo` to `schemacmp.Table`
	4. call schemacmp.Table.String()
	5. get 
	  ```sql
	  CREATE TABLE `tbl`(`a` INT(11) NOT NULL, `b` INT(11), PRIMARY KEY USING  (`a`(0))) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN
	  ```

2. What did you expect to see?
```
CREATE TABLE `tbl`(`a` INT(11) NOT NULL, `b` INT(11), PRIMARY KEY  (`a`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN
```
3. What did you see instead?
```
CREATE TABLE `tbl`(`a` INT(11) NOT NULL, `b` INT(11), PRIMARY KEY USING  (`a`(0))) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN
```
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

### reason

https://github.com/pingcap/tidb-tools/blob/d9fdfa2f9040aab3fab7cd11774a82226f467fe7/pkg/dbutil/table.go#L59-L73

not assign `model.IndexInfo.Tp` and `model.IndexInfo.Column.Length`

**Comment by lance6716** [comment]
how does it happen? `Key part 'a' length cannot be 0`

**Comment by okJiang** [comment]
the reason updated @lance6716
