### ISSUE TITLE
sync_diff_inspector: different time_zone check output has 8 hours gap

### ISSUE THREAD

**Issue by 15767637775** [pingcap/tidb-tools#591]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
  If possible, provide a recipe for reproducing the error.
        sync_diff_inspector
        upstream's timezone was CST,
        downstream's timezone was UTC
  
        \# upstream
        mysql> select * from sbtest1;
        +----+---------------------+
        | id | update_time         |
        +----+---------------------+
        |  1 | 2022-01-29 23:21:12 |
  
        the output of fix.sql will be unexpected , the gap was 8 hours:
        \# fix.sql
        REPLACE INTO `sbtest`.`sbtest1`(`id`,`update_time`) VALUES (1,'2022-01-29 15:21:12');
  
        related link: https://kjz3me1ksu.feishu.cn/docs/doccnTA11QLGCeXTbsuF4Ey1yib

2. What did you expect to see?
The timezone can be configurable or the output of fix.sql is based on the downstream's timezone.
Let sync_diff_inspector support compare between cluster with different default time_zone.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v5.3.0

5. which tool are you using?
sync_diff_inspector
![middle_img_v2_34df1066-4806-4a4f-8845-96975635247g](https://user-images.githubusercontent.com/71695537/153393722-296a232a-8e9b-4263-b193-618e681c8db0.png)

6. what version of tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?
sync_diff_inspector v2.0

**Comment by Leavrth** [comment]
It seems that the value of type `timestamp` is decided by `time_zone`.
```
mysql> show create table t1;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` int(11) NOT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> set @@session.time_zone = "+0:00";
Query OK, 0 rows affected (0.00 sec)

mysql> replace into `test`.`t1` (`id`, `update_time`) values (1, '2022-01-29 15:21:12');
Query OK, 1 row affected (0.01 sec)

mysql> set @@session.time_zone = "+8:00";
Query OK, 0 rows affected (0.00 sec)

mysql> replace into `test`.`t1` (`id`, `update_time`) values (2, '2022-01-29 23:21:12');
Query OK, 1 row affected (0.01 sec)

mysql> select * from `test`.`t1`;
+----+---------------------+
| id | update_time         |
+----+---------------------+
|  1 | 2022-01-29 23:21:12 |
|  2 | 2022-01-29 23:21:12 |
+----+---------------------+
2 rows in set (0.00 sec)
```

**Comment by 15767637775** [comment]
yes, I close this issue.
