### ISSUE TITLE
sync-diff-inspector:filter sequence

### ISSUE THREAD

**Issue by cartersz** [pingcap/tidb-tools#609]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when get tables from schema, "GetTables" method in common.go do not filter sequence

2. What did you expect to see?
it can filter sequence

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5. which tool are you using?

6. what versionof tool are you using (`pump -V` or `tidb-lightning -V` or `syncer -V`)?

**Comment by kennytm** [comment]
fixed since v5.3.2 in #610.
