### ISSUE TITLE
Duplicated table-router in tidb-tools and tidb/util

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tidb-tools#625]
`table-router` in this repo and the one in tidb should be the same. tiflow used to invoke the `table-router` from this repo but now replaces it with the one in tidb. Usually, there is no concern though they use different `table-router` in their own repo, however, when we try to simultaneously invoke the tidb-tools and the tiflow repo, an unexpected error occurs:
```
../../../../go/pkg/mod/[github.com/pingcap/tidb-tools@v6.0.1-0.20220516050036-b3ea358e374a+incompatible/sync_diff_inspector/config/config.go:411:31](http://github.com/pingcap/tidb-tools@v6.0.1-0.20220516050036-b3ea358e374a+incompatible/sync_diff_inspector/config/config.go:411:31): cannot use rule (variable of type *"[github.com/pingcap/tidb/util/table-router](http://github.com/pingcap/tidb/util/table-router)".TableRule) as type *"[github.com/pingcap/tidb-tools/pkg/table-router](http://github.com/pingcap/tidb-tools/pkg/table-router)".TableRule in argument to tableRouter.AddRule
``` 
This is because the latest tiflow uses `table-router` in tidb and in the meanwhile, the `sync_diff_inspector` package in tidb-tools invokes tiflow's package, which confuses the compiler with the two namesakes.

The `table-router` would better be the same across these repos.

**Comment by AkiraXie** [comment]
when I use tiflow and tidb-tools in one project, this issue causes a TypeError when building:
` # github.com/pingcap/tidb-tools/sync_diff_inspector/config
/root/go/pkg/mod/github.com/pingcap/tidb-tools@v6.1.0+incompatible/sync_diff_inspector/config/config.go:411:31: cannot use rule (variable of type *"github.com/pingcap/tidb/util/table-router".TableRule) as type *"github.com/pingcap/tidb-tools/pkg/table-router".TableRule in argument to tableRouter.AddRule.
`
just like the author said, so please handle the issue, thanks!
