### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by gqf2008** [pingcap/tidb-tools#68]
make build
GO15VENDOREXPERIMENT="1" go build -o bin/importer ./importer
# github.com/pingcap/tidb/parser
/var/lib/gopath/src/github.com/pingcap/tidb/parser/lexer.go:95: undefined: yySymType
/var/lib/gopath/src/github.com/pingcap/tidb/parser/misc.go:518: undefined: yySymType
/var/lib/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:60: undefined: yySymType
/var/lib/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:61: undefined: yySymType
/var/lib/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:62: undefined: yySymType
make: *** [importer] 错误 2

**Comment by ngaut** [comment]
Please enter the tidb source directory, in your machine,  the path should be "/var/lib/gopath/src/github.com/pingcap/tidb". Update tidb to the lastest version,  then run command "make parser" first.
