### ISSUE TITLE
Syncer execute sql error 

### ISSUE THREAD

**Issue by cwen0** [pingcap/tidb-tools#71]
db.go:389: [error] Parser SQL error: ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' AS '*password'

**Comment by cwen0** [comment]
new error:
db.go:389: [error] Parser SQL error: drop user fin_user@'192.168.2.*'

**Comment by nolouch** [comment]
cc @tiancaiamao

**Comment by andelf** [comment]
partially fixed by #73

**Comment by tiancaiamao** [comment]
which tool generate this kind of SQL ?
