### ISSUE TITLE
Syncer gen insert sqls failed 

### ISSUE THREAD

**Issue by cwen0** [pingcap/tidb-tools#72]
2017/02/23 14:39:48 main.go:79: [error] /home/pingcap/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:580: gen insert sqls failed: invalid columns and data - 6, 7, schema: financeent, table: user
/home/pingcap/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:125:

**Comment by andelf** [comment]
This is caused by schema mismatch. for binlog syncing, this indicates wrong pos
