### ISSUE TITLE
session level statement format binlogs cause syncer fatal error

### ISSUE THREAD

**Issue by chenmin1992** [pingcap/tidb-tools#77]
```
2018/10/10 11:44:49 syncer.go:691: [info] [query]delete from database.table where xdy_id = 0 and order_push = '' LIMIT 10000 [current pos](mysql-bin.000342, 45411735) [next pos](mysql-bin.000342, 45412052) [current gtid set]6c8a10ed-ed0b-11e4-91eb-00163ec546ca:474850265-545675226,b5d40430-394b-11e7-8dcf-1866daeaae14:1-10,b5d40430-394b-11e7-8dcf-2381daeaae14:1-200688052 [next gtid set]6c8a10ed-ed0b-11e4-91eb-00163ec546ca:474850265-545675226,b5d40430-394b-11e7-8dcf-1866daeaae14:1-10,b5d40430-394b-11e7-8dcf-2381daeaae14:1-200688038
2018/10/10 11:44:49 syncer.go:697: [error] fail to be parsed, error query delete from database.table where xdy_id = 0 and order_push = '' LIMIT 10000: unexpected dml statement found in query event
2018/10/10 11:44:49 syncer.go:962: [info] flush all jobs meta = syncer-binlog = (mysql-bin.000342, 45411735), syncer-binlog-gtid = b5d40430-394b-11e7-8dcf-1866daeaae14:1-10,b5d40430-394b-11e7-8dcf-2381daeaae14:1-200688057,6c8a10ed-ed0b-11e4-91eb-00163ec546ca:474850265-545675226
2018/10/10 11:44:49 meta.go:137: [info] save position to file, binlog-name:mysql-bin.000342 binlog-pos:45411735 binlog-gtid:6c8a10ed-ed0b-11e4-91eb-00163ec546ca:474850265-545675226,b5d40430-394b-11e7-8dcf-1866daeaae14:1-10,b5d40430-394b-11e7-8dcf-2381daeaae14:1-200688037
2018/10/10 11:44:49 main.go:79: [error] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/ddl.go:29: unexpected dml statement found in query event
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/ddl.go:76: query delete from database.table where xdy_id = 0 and order_push = '' LIMIT 10000
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:698: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:179:  
2018/10/10 11:44:49 syncer.go:872: [info] print status exits, err:context canceled
```

the purpose of this issue is only requestting feature that syncer can recognize and skip  statement format binlogs. thanks.

**Comment by kennytm** [comment]
Hi, thanks for the enhancement request.

Syncer only supports the ROW binlog format, not STATEMENT or MIXED. We have also added a check in the next release version for the binlog format, and will abort if the setting is incorrect.

**Comment by chenmin1992** [comment]
I mean it will make the replication broken if there is any irregular client who set session level binlog format to STATEMENT. I think we should avoid this case to stop running syncer. and setting is correct fully.

**Comment by csuzhangxc** [comment]
Hi, thanks for your requests. 
But we have no plans to support this feature recently.
If we skip statement format binlogs and user set binlog format incorrectly, then him may say "my data lost".

For what reason, you must set session level binlog format to STATEMENT?

**Comment by chenmin1992** [comment]
because someone doesn't know  we can't set binlog format to STATEMENT.

**Comment by csuzhangxc** [comment]
you must read the doc first.
English ver: https://github.com/pingcap/docs/blob/master/tools/syncer.md#check-before-importing-data-using-syncer
Chinese ver: https://github.com/pingcap/docs-cn/blob/master/tools/syncer.md#syncer-%E5%90%8C%E6%AD%A5%E5%89%8D%E6%A3%80%E6%9F%A5

> because someone doesn't know we can't set binlog format to STATEMENT.

This is why we do not choose to skip statement format binlogs. We think reporting error is better than doing wrong things.
