### ISSUE TITLE
syncer: improve config

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb-tools#79]
support like 
```
[[replicate-do-table]]
db-name ="db1"
tbl-name = ["table1","table2"]'
```

**Comment by siddontang** [comment]
For compatibility, we may use `tbl-names`

**Comment by andelf** [comment]
why not:

```
do-tables = ["db1.table1", "db1.table2"]
db-tables = ["db1.table%"]
```

``--replicate-do-table`` is the command line argument for `mysql`,
for syncer, the executable name already tells us what it does is to do replication.

btw, to specify a regexp，use `~` as prefix is weird. should use `/a_reg_exp/`.

**Comment by GregoryIan** [comment]
done
