### ISSUE TITLE
checker doesn't support IPv6

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb-tools#85]
[root@echo-deployment-pvc-cccdf664b-8fszp bin]# ./checker **-host 2002:ac1f:91c6::1** -port 10528 -user root -password test test
2018/10/22 09:19:36 main.go:74: [fatal] create database connection failed: dial tcp: address 2002:ac1f:91c6::1:10528: too many colons in address

It would be good to support IPv6 as it is being used widely today, can you consider this quick support in recent plan?

**Comment by kennytm** [comment]
Hi, thanks for your interest.

Checker does support IPv6, but you need to surround the address in square brackets:

```sh
./checker -host '[2002:ac1f:91c6::1]' -port 10528 -user root -password test test
#                ^                 ^
```

**Comment by CrazyNash** [comment]
it works, thank you for your efficient support
