### ISSUE TITLE
checker IPv6 support

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb-tools#86]
checker dosn't support IPv6 host address at present, it's required by my project.

Not sure why my previous issue got deleted, but I would like to request this again.

Pls let me know why when you delete this request, thanks!

**Comment by kennytm** [comment]
Hi, there was a [major outage on GitHub](https://blog.github.com/2018-10-21-october21-incident-report/) today which put the site in read-only mode for more than 10 hours, which is probably why #85 wasn't initially visible. Since the other is back I'm closing this as duplicate of #85. Thanks.
