### ISSUE TITLE
如何从阿里云的rds同步数据？

### ISSUE THREAD

**Issue by wangcn** [pingcap/tidb-tools#90]
syncer依赖binlog，但阿里云rds的binlog会定时挪走。对这种情况有什么同步方案建议？

**Comment by siddontang** [comment]
syncer 可以考虑快速同步到本地，然后在同步给 tidb
但通常 rds 挪走的时候，syncer 也能同步完吧

**Comment by wangcn** [comment]
有可能大表的存量数据还没有同步完，就到了binlog归档的时间。

**Comment by wangcn** [comment]
刚才试了下syncer，需要同步的db配置为
replicate-do-db = ["src_db"]
replicate-ignore-db = ["test"]
运行时发现仍然尝试同步test库，并且报错，log如下
2017/03/09 20:26:13 db.go:389: [error] error while parsing sql: # Dum
2017/03/09 20:26:13 syncer.go:643: [warning] [skip query-sql]# Dum  [schema]:
2017/03/09 20:26:13 db.go:389: [error] error while parsing sql: rename /* gh-ost */ table `test`.`member_copy` to `test`.`_member_copy_del`, `test`.`_member_copy_gho` to `test`.`member_copy`
2017/03/09 20:26:13 main.go:75: [error] /home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:646: parse query event failed: line 0 column 76 near " `test`.`_member_copy_gho` to `test`.`member_copy`" (total length 126), position (mysql-bin.000002, 193021589)
/home/jenkins/workspace/TIDB_TOOLS_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb-tools/syncer/syncer.go:118:  

syncer版本：
syncer: v1.0.0~rc2+git.f2e0ce9
Git Commit Hash: f2e0ce91bec799a4ca8864be1dde9d6be04ba867
UTC Build Time: 2017-03-07 10:42:33
Go Version: go1.7.3

**Comment by c4pt0r** [comment]
maybe u clould use [dts](https://help.aliyun.com/knowledge_list/41820.html).

**Comment by siddontang** [comment]
现在我们应该还不支持 rename 操作吧 @shenli

**Comment by shenli** [comment]
We support rename table statement: https://github.com/pingcap/tidb/blob/master/parser/parser.y#L1071
But we could only rename one table in a DDL.
@wangcn

**Comment by ruiaylin** [comment]
外部应用是无法获取rds的binlog的 , 只能用dts 做数据迁移.
